/**
 * E7 — Fab/quote attach workflow. NO automatic ordering, ever.
 *
 * The state machine encodes the commercial model (platform + credits +
 * fab attach) while keeping every outward step MANUAL: quote submission
 * and order submission are recorded as *_manually states via explicit
 * human entry; approved_for_quote / approved_for_order transitions verify
 * an approved approval record before they move. Quote received is not
 * physical evidence; order submitted is not physical validation.
 */
import fs from 'node:fs'
import path from 'node:path'
import { newId, appendAudit, APP_ROOT } from './store.mjs'

export const QUOTE_STATES = [
  'package_not_ready', 'package_ready_with_review', 'quote_packet_ready',
  'quote_approval_requested', 'approved_for_quote',
  'quote_submitted_manually', 'quote_received', 'approved_for_order',
  'order_submitted_manually', 'fab_in_progress',
  'boards_received_pending_evidence', 'blocked',
]

// legal transitions; approval-gated ones carry the approval type they need
const TRANSITIONS = {
  package_not_ready: ['package_ready_with_review'],
  package_ready_with_review: ['quote_packet_ready', 'blocked'],
  quote_packet_ready: ['quote_approval_requested', 'blocked'],
  quote_approval_requested: ['approved_for_quote', 'blocked'],
  approved_for_quote: ['quote_submitted_manually', 'blocked'],
  quote_submitted_manually: ['quote_received', 'blocked'],
  quote_received: ['approved_for_order', 'blocked'],
  approved_for_order: ['order_submitted_manually', 'blocked'],
  order_submitted_manually: ['fab_in_progress', 'blocked'],
  fab_in_progress: ['boards_received_pending_evidence', 'blocked'],
  boards_received_pending_evidence: ['blocked'],
  blocked: ['package_ready_with_review'],
}

const APPROVAL_GATED = {
  approved_for_quote: 'approved_for_quote',
  approved_for_order: 'approved_for_order',
}

// states that require an explicit manual-entry record (a human did the
// outward action OUTSIDE the platform and reports it here)
const MANUAL_ENTRY = new Set(['quote_submitted_manually', 'quote_received',
                              'order_submitted_manually', 'fab_in_progress',
                              'boards_received_pending_evidence'])

export function generateQuotePacket(db, { board_id, special_requirements = [],
                                          actor }) {
  const b = db.boards.find((x) => x.board_id === board_id)
  if (!b) return { error: 'no such board' }
  const run = db.runs.find((r) => r.run_id === b.latest_run_id)
  if (!run?.source_run_dir) {
    return { error: 'no attached run — package_not_ready' }
  }
  const dataDir = path.join(APP_ROOT, 'public', 'runs', run.source_run_dir,
                            'data')
  const files = fs.existsSync(dataDir) ? fs.readdirSync(dataDir) : []
  const approvals = db.approvals.filter(
    (a) => a.scope?.board_id === board_id)
  const packet = {
    schema: 'quote-packet/v1',
    board_id, run_dir: run.source_run_dir,
    generated_at: new Date().toISOString(),
    contents: {
      board_files: [`public/runs/${run.source_run_dir}/variant.kicad_pcb`],
      gerbers_drill: 'fab package zip (generated by the pipeline export '
        + 'step; regenerate via export_fab.py if absent)',
      bom: files.includes('bom.json')
        ? `public/runs/${run.source_run_dir}/data/bom.json` : null,
      pick_and_place: files.includes('pick_and_place.csv')
        ? `public/runs/${run.source_run_dir}/data/pick_and_place.csv` : null,
      step: 'included in fab package when generated',
      stackup_assumptions: 'STANDARD fab stackup assumed — NO controlled '
        + 'impedance (no stackup data in repo; claim blocked)',
      drc_erc: { drc: run.drc_state, erc: run.erc_state },
      router_evidence: run.route_evidence_state,
      review_required_labels: b.review_required_items,
      blocked_claims: b.blocked_claims,
      special_fab_requirements: special_requirements,
      human_approval_snapshot: approvals.map((a) => ({
        type: a.approval_type, status: a.status, approver: a.approver })),
    },
    honesty: 'quote packet describes a review-required package; a received '
      + 'quote is not physical evidence',
  }
  let q = db.quotes.find((x) => x.board_id === board_id)
  if (!q) {
    q = { quote_id: newId('qte'), board_id,
          state: 'package_ready_with_review',
          fab_vendor: { name: null, contact: null,
                        note: 'vendor metadata placeholder — no '
                          + 'integration, no automatic contact' },
          fab_attach: { tracked: true, revenue_placeholder: null,
                        note: 'internal metadata only' },
          packet: null, manual_entries: [], history: [] }
    db.quotes.push(q)
  }
  q.packet = packet
  q.state = q.state === 'package_not_ready'
    ? 'package_ready_with_review' : q.state
  if (q.state === 'package_ready_with_review') q.state = 'quote_packet_ready'
  q.history.push({ state: q.state, at: packet.generated_at,
                   note: 'quote packet generated' })
  appendAudit(db, { actor, action: 'generate_quote_packet',
                    scope: { board_id }, after: { state: q.state } })
  return q
}

export function advanceQuote(db, { board_id, to, note = '', actor }) {
  const q = db.quotes.find((x) => x.board_id === board_id)
  if (!q) return { error: 'no quote workflow for board' }
  if (!QUOTE_STATES.includes(to)) return { error: `unknown state ${to}` }
  if (!(TRANSITIONS[q.state] ?? []).includes(to)) {
    return { error: `illegal transition ${q.state} -> ${to}` }
  }
  const gate = APPROVAL_GATED[to]
  if (gate) {
    const ok = db.approvals.some(
      (a) => a.scope?.board_id === board_id && a.approval_type === gate
        && a.status === 'approved')
    if (!ok) {
      appendAudit(db, { actor, action: 'quote_transition_REFUSED',
                        scope: { board_id },
                        after: { attempted: to },
                        note: `requires approved ${gate} record` })
      return { error: `${to} requires an approved ${gate} approval record — `
                      + 'it cannot be inferred or automated' }
    }
  }
  if (MANUAL_ENTRY.has(to) && !note) {
    return { error: `${to} is a MANUAL entry — a human must describe the `
                    + 'action they performed outside the platform' }
  }
  const before = q.state
  q.state = to
  const entry = { state: to, at: new Date().toISOString(), note }
  q.history.push(entry)
  if (MANUAL_ENTRY.has(to)) q.manual_entries.push(entry)
  appendAudit(db, { actor, action: 'advance_quote', scope: { board_id },
                    before: { state: before }, after: { state: to }, note })
  return q
}

export function quoteWorkflowReport(db) {
  return {
    generated_at: new Date().toISOString(),
    states: QUOTE_STATES,
    quotes: db.quotes.map((q) => ({
      quote_id: q.quote_id, board_id: q.board_id, state: q.state,
      manual_entries: q.manual_entries.length,
      history: q.history })),
    rules: [
      'no automatic quote submission — quote_submitted_manually requires '
      + 'human manual entry with a note',
      'no automatic order submission — same mechanism',
      'approved_for_quote / approved_for_order verify an approved approval '
      + 'record at transition time',
      'quote_received is not physical evidence',
      'order_submitted is not physical validation',
      'boards_received_pending_evidence still requires evidence upload + '
      + 'review before any physical claim',
      'fab attach is internal metadata only',
    ],
  }
}

// dispatcher handlers ---------------------------------------------------------
export function handlers(db, actor) {
  return {
    generate_quote_packet: (p) => generateQuotePacket(db, { ...p, actor }),
    advance_quote: (p) => advanceQuote(db, { ...p, actor }),
    quote_workflow_report: () => quoteWorkflowReport(db),
  }
}
