export const metadata = { title: "Terms of Use, FirstLight" };

export default function Terms() {
  return (
    <main className="legal-page">
      <div className="container narrow">
        <p className="kicker">StarDrive Inc.</p>
        <h1>Terms of Use</h1>
        <p className="legal-updated">Last updated: July 5, 2026</p>

        <p>
          These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of the
          FirstLight website, the FirstLight Compose software platform, and related
          services (together, the &ldquo;Services&rdquo;), operated by StarDrive Inc.
          (&ldquo;StarDrive,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;). By accessing or
          using the Services you agree to these Terms. If you do not agree, do not use
          the Services.
        </p>

        <h2>1. The Services</h2>
        <p>
          FirstLight Compose generates printed circuit board designs, bills of
          materials, fabrication files, firmware, test plans, and related engineering
          artifacts from user descriptions, using automated design tools and
          artificial-intelligence models. The Services are under active development and
          are provided as a preview; features may change, be interrupted, or be
          discontinued at any time.
        </p>

        <h2>2. Accounts</h2>
        <p>
          You must create an account to use Compose. You are responsible for
          safeguarding your credentials and for all activity under your account. You
          must provide accurate information and be at least 18 years old. We may
          suspend or terminate accounts that violate these Terms.
        </p>

        <h2>3. Plans, Billing, and Cancellation</h2>
        <p>
          The free plan includes a limited number of board-generation runs per month.
          Paid subscriptions (&ldquo;Pro&rdquo;) are billed in advance on a monthly
          basis through our payment processor, Stripe; we do not store your card
          details. Subscriptions renew automatically until cancelled. You may cancel at
          any time, effective at the end of the current billing period; fees already
          paid are non-refundable except where required by law. We may change pricing
          with at least 30 days&rsquo; notice.
        </p>

        <h2>4. Your Content and Designs</h2>
        <p>
          You retain ownership of the descriptions you submit and, as between you and
          StarDrive, the design outputs generated for you (board files, gerbers,
          BOMs, firmware, test plans). We claim no ownership of your designs. You grant
          us a limited license to process, store, and display your content solely to
          operate and improve the Services. We own the Services themselves, including
          the platform, pipeline, block library, and models.
        </p>

        <h2>5. Hardware Disclaimer, Read This One</h2>
        <p>
          Design outputs are generated by automated tools and ARE PROVIDED FOR
          ENGINEERING EVALUATION ONLY. They may contain errors. Passing our automated
          checks (DRC, ERC, or otherwise) is not a representation that a design is
          safe, functional, manufacturable, or fit for any purpose. You are solely
          responsible for reviewing and validating any design before fabricating,
          assembling, powering, deploying, or certifying it, and for compliance with
          all applicable safety and regulatory requirements. StarDrive is not liable
          for fabrication costs, component costs, property damage, or any consequence
          of manufacturing or operating hardware derived from the Services. Do not use
          design outputs in safety-critical, life-support, medical, nuclear, or
          similar applications without independent qualified engineering review and
          certification.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>
          You will not: misuse or overload the Services; attempt to access other
          users&rsquo; data; reverse engineer non-public parts of the platform; use the
          Services to design devices intended to cause harm or that are illegal under
          applicable law, including applicable export-control regulations (EAR/ITAR);
          or resell the Services without our written agreement.
        </p>

        <h2>7. Third-Party Services</h2>
        <p>
          The Services interoperate with third parties, including payment processing
          (Stripe), AI model providers, component distributors, and sign-in providers
          (Google). Their services are governed by their own terms. If you supply your
          own AI provider API key, you are responsible for that provider&rsquo;s fees
          and terms.
        </p>

        <h2>8. Disclaimer of Warranties</h2>
        <p>
          THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo;
          WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, STARDRIVE&rsquo;S TOTAL LIABILITY
          ARISING OUT OF OR RELATING TO THE SERVICES WILL NOT EXCEED THE AMOUNTS YOU
          PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM, AND STARDRIVE WILL NOT BE
          LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
          OR LOST PROFITS, DATA, OR GOODWILL.
        </p>

        <h2>10. Termination</h2>
        <p>
          You may stop using the Services at any time. We may suspend or terminate
          your access for breach of these Terms. Sections 4, 5, 8, 9, and 11 survive
          termination.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the State of California, USA,
          without regard to conflict-of-law rules. Exclusive venue lies in the state
          and federal courts located in California.
        </p>

        <h2>12. Changes</h2>
        <p>
          We may update these Terms; material changes will be posted on this page with
          an updated date. Continued use after changes constitutes acceptance.
        </p>

        <h2>Contact</h2>
        <p>
          StarDrive Inc., <a href="mailto:jack@thestardrive.com">jack@thestardrive.com</a>
        </p>

        <p>
          <a href="/" className="compose-link">&larr; Back to FirstLight</a>
        </p>
      </div>
    </main>
  );
}
