"""Contract-manufacturer abstraction — the customer-facing "get a real assembly
quote / order this board" layer. The UI/pipeline calls quote_board() and never
touches a specific CM's API, so MacroFab can be swapped for Pikkolo / PCBWay /
JLCPCB later without changing the workflow.

Today: MacroFab backend. It maps our composed board (board.json + bom.json +
the routed .kicad_pcb placement) into MacroFab's project, uploads the BOM, and
requests a quote.

  manufacturer.py quote <board.kicad_pcb> <bom.json> <board.json> [qty]
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import macrofab as mf
from digikey import load_env


# ---- mapping our data -> MacroFab -------------------------------------------
def _pkg_from_footprint(fp):
    """'Package_SO:SOIC-8_3.9x4.9mm_P1.27mm' -> 'SOIC-8'; '..C_0402..' -> '0402'."""
    name = fp.split(":")[-1]
    m = re.search(r"(\d{4})Metric|_(\d{4})_|-(\d+)_|^([A-Z]+-?\d+)", name)
    if m:
        return next((g for g in m.groups() if g), name)
    return name[:24]


def _mpn_from_part(part):
    """Our BOM 'part' is 'YAGEO CC0603KRX7R9BB104 — 100nF ...'; pull the MPN-ish
    token (the longest alnum run that looks like a part number)."""
    toks = re.findall(r"[A-Z0-9][A-Z0-9\-/]{4,}", (part or "").upper())
    return toks[0] if toks else None


def map_bom(bom):
    """our bom.json [{ref, part, lcsc, qty, ...}] -> MacroFab BOM parts."""
    parts = []
    for i, line in enumerate(bom):
        ref = line.get("ref") or (line.get("refs") or [""])[0]
        parts.append({
            "record_num": i,
            "part": ref,
            "origin": "turnkey",  # MacroFab sources the part
            "value": line.get("value") or "",
            "package": _pkg_from_footprint(line.get("footprint", "")),
            "populate": True,
            "mpn": line.get("mpn") or _mpn_from_part(line.get("part", "")),
        })
    return [p for p in parts if p["part"]]


def xyrs_from_board(board_pcb):
    """Extract placement (XYRS) by parsing the .kicad_pcb text — no pcbnew, so
    this runs under system Python (KiCad's Python has a broken SSL store)."""
    try:
        text = open(board_pcb).read()
    except Exception:
        return []
    out = []
    for blk in re.split(r"\n  \(footprint ", text)[1:]:
        fp = re.match(r'"([^"]+)"', blk)
        at = re.search(r"\(at ([\d.-]+) ([\d.-]+)(?: ([\d.-]+))?\)", blk)
        ref = re.search(r'\(property "Reference" "([^"]+)"', blk)
        val = re.search(r'\(property "Value" "([^"]+)"', blk)
        if not (fp and at and ref):
            continue
        name = fp.group(1).split(":")[-1]
        pth = bool(re.search(r'\(pads?[^)]*thru_hole', blk)) or "thru_hole" in blk
        out.append({
            "designator": ref.group(1),
            "x_loc": float(at.group(1)),
            "y_loc": float(at.group(2)),
            "rotation": float(at.group(3) or 0),
            "board_side": "bottom" if '(layer "B.Cu")' in blk.split("\n")[0] else "top",
            "component_type": "PTH" if pth else "SMT",
            "x_size": 1.0,
            "y_size": 1.0,
            "value": val.group(1) if val else name,
            "footprint": name,
        })
    return out


# ---- the abstraction --------------------------------------------------------
def quote_board(board_pcb, bom, board_json, quantity=10, name="FirstLight board"):
    """Create a CM project from our board, upload the BOM + placement, and return
    a normalized quote dict. Backend: MacroFab. Returns enough for the UI to show
    the project + price (or the current blocker)."""
    load_env()
    layers = board_json.get("layers", 2)
    pcb_id = mf.create_pcb(name, "Generated by FirstLight prompt-to-PCBA")
    result = {"manufacturer": "macrofab", "pcb_id": pcb_id,
              "dashboard": "https://macrofab.com/pcb/%s" % pcb_id,
              "layers": layers, "quantity": quantity}

    parts = map_bom(bom)
    s, d = mf.add_bom_parts(pcb_id, 1, parts)
    result["bom_uploaded"] = (s == 200)
    result["bom_lines"] = len(parts)

    xyrs = xyrs_from_board(board_pcb)
    s, d = mf.upload_xyrs(pcb_id, 1, xyrs)  # placement; format still firming up
    result["placement_uploaded"] = (s == 200)
    result["placement_parts"] = len(xyrs)

    s, q = mf.get_quote(pcb_id, 1, quantity, layer_count=layers, manufacturing="Standard")
    if s == 200:
        result["quote"] = q
        result["status"] = "quoted"
    else:
        result["status"] = "project_created"  # BOM in; quote needs files finalized
        result["quote_http"] = s
    return result


def main():
    load_env()
    if len(sys.argv) < 4 or sys.argv[1] != "quote":
        print(__doc__)
        return
    board_pcb, bom_path, board_path = sys.argv[2:5]
    qty = int(sys.argv[5]) if len(sys.argv) > 5 else 10
    bom = json.load(open(bom_path))
    board_json = json.load(open(board_path))
    r = quote_board(board_pcb, bom, board_json, qty)
    print(json.dumps(r, indent=1)[:1500])


if __name__ == "__main__":
    main()
