"""Cosmetic finish pass record — 2026-06-11 session.

Matched the CAD to the approved industrial-design renders entirely through
the API (zero Adam tokens). This file is the authoritative record of what
was done and the final geometry; the reusable feature builders it exercised
live in features.py (delete_bodies, transform_translate, fillet_edge_at,
add_extrude_remove, rounded_rect/arc).

Sequence executed (chronological):

 1. PALETTE — render colors over the enclosure (see PALETTE below), smoked
    glass via appearance opacity.
 2. EMBLEM — "Probe Head Logo Emblem": O20 x 2 blue disc on the probe head
    front face.
 3. GAP TRIM — six filler panels closing the slots between the face panels
    and the shells (rear sides, front sides/sill/header).
 4. TOP REBUILD (iterated) — deleted the misfit Adam top (35 mm buried in
    each shell); final state is the contoured slab below.
 5. REAR FLUSH — transform_translate of the whole 28-body rear cluster
    +58 mm in Y so the panel face is coplanar with the shell backs (Y=460).
    Sketches do NOT move with transforms — hide them in the UI afterwards.
 6. FRONT FLUSH — per-layer shifts (fascia -45, surround/glass -50,
    trim -52) landing every outer face at Y=-460; glass later pulled to
    dead-flush at -460.
 7. GLASS FRAME — replaced the solid surround with a 4-strip frame around
    the glass opening; glass opacity 55/255 so the mechanism reads through.
 8. POWER CLUSTER — rounded bezel + button + LED bar + dot on the front
    right filler band; later moved to lower right (transform dz -290).
    Old side-stub power button deleted.
 9. E-STOP + SWEPT VOLUMES — deleted from the cosmetic model. The physical
    EVT build still requires a hardware e-stop on the guarding; the swept
    volumes are analysis bodies, regenerated by build_run4_sensors_swept.py
    whenever an audit runs.
10. SIDE VENTS — 132 O5 holes (16 mm grid, Y -420..-260, Z 240..420) cut
    through BOTH shells with one Right-plane sketch + one scoped REMOVE
    extrude spanning the full width (booleanScope = the two shells).
11. CONTOURED TOP (final) — "Top Slab" X +/-435, Y +/-460, Z 452..482 with
    R30 roundovers front AND rear, matching the shells' measured top-edge
    radius (evSurfaceDefinition over the shell's cylindrical faces: R30 top
    edges, R60 vertical corners, R2.5 vents). To clear the R30 curve, all
    face assemblies top out at Z=452: front frame/fillers rebuilt, rear
    panel + fillers cut by a SCOPED REMOVE extrude inset to X +/-436 — the
    earlier cut failures were the cut boundary exactly coincident with the
    filler faces at X=435.

Known residue (manual cleanup): one errored feature "EVT - Rear Top Cut"
+ its sketch in the tree (delete in UI); rear top screw row sits 10 mm
lower than original (moved for the abandoned cut; harmless).

Final front-plane stack (outer faces):
    fascia/surround/trim/glass at Y=-460 (glass 4 mm thick, frame strips
    X +/-(375..395)); accent strip 1 mm proud at the fascia lower edge.
Final rear plane: panel + fillers at Y=460, connectors/labels/screws proud.
Top: slab Z 452-482 flush between shells, R30 roundovers both ends mating
the shell contour exactly.
"""

from __future__ import annotations

import time
import warnings

warnings.filterwarnings("ignore")

from urllib.parse import quote

from features import FeatureBuilder
from onshape_client import Client

DID = "02ed72e43f8d925e0c7aa678"
WID = "80299bfade6ea16b1cd86a0e"
EID = "8a871c2acd668dc865dda723"

APPEARANCE_PROP = "57f3fb8efa3416c06701d60c"
NAME_PROP = "57f3fb8efa3416c06701d60d"

#: default plane deterministic IDs (probed empirically in this document)
PLANE_TOP = "JDC"      # sketch (x,y) -> world (X,Y), extrude +Z
PLANE_FRONT = "JCC"    # sketch (x,y) -> world (X,Z), extrude -Y
PLANE_RIGHT = "JEC"    # sketch (x,y) -> world (+Y,Z), extrude +X

#: final render palette: name -> (r, g, b, opacity)
PALETTE = {
    "Side Shell Left": (242, 241, 238, 255),
    "Side Shell Right": (242, 241, 238, 255),
    "Top Slab": (245, 245, 243, 255),
    "Rear Matte Black Panel": (38, 38, 40, 255),
    "Rear Vent Baffle": (12, 12, 14, 255),
    "Front Smoked Glass v2": (25, 30, 38, 55),
    "Glass Frame Side L+R": (22, 22, 25, 255),
    "Glass Frame Bottom": (22, 22, 25, 255),
    "Glass Frame Top": (22, 22, 25, 255),
    "Plinth Fascia": (18, 18, 20, 255),
    "Accent Light Strip Full Width": (60, 130, 255, 255),
    "Power Bezel": (28, 28, 31, 255),
    "Power Button": (70, 140, 255, 255),
    "Power LED Bar": (150, 190, 255, 255),
    "Power Indicator Dot": (90, 90, 95, 255),
    "Chamber Light Bar": (250, 250, 255, 255),
    "Enclosure Base Pan": (30, 30, 32, 255),
    "Probe Head Logo Emblem": (70, 150, 255, 255),
    "Trim - Rear Filler Left": (38, 38, 40, 255),
    "Trim - Rear Filler Right": (38, 38, 40, 255),
    "Trim - Front Filler L+R": (22, 22, 25, 255),
    "Trim - Front Sill": (22, 22, 25, 255),
}


def apply_palette() -> None:
    """Re-apply the render palette (safe to re-run any time)."""
    c = Client()
    parts = {p["name"]: p["partId"] for p in c.list_parts(DID, WID, EID)}
    for name, (r, g, b, op) in PALETTE.items():
        if name not in parts:
            print("missing:", name)
            continue
        c._request(
            "POST", "/api/v6/metadata/d/{}/w/{}/e/{}/p/{}".format(
                DID, WID, EID, quote(parts[name], safe="")),
            json={"properties": [{"propertyId": APPEARANCE_PROP,
                  "value": {"color": {"red": r, "green": g, "blue": b},
                            "opacity": op}}]})
        time.sleep(0.3)
    print("palette applied")


if __name__ == "__main__":
    apply_palette()
