"""Curated FL-1 reference library seed (Phase 13 D.5).

References are EVIDENCE and pattern guidance, never trusted reusable designs. Only
internal FirstLight designs (or explicitly license-reviewed ones) may be reused;
everything external defaults to direct_reuse=false. Nothing here copies an external
schematic/layout/BOM, and nothing is scraped — external entries without a local
file are honest placeholders marked needs_source_file.
"""
import json

TRUST = ("internal_firstlight", "manufacturer_reference_only",
         "open_source_needs_license_review", "licensed_reusable",
         "idea_only", "unknown_untrusted")
REUSABLE = ("internal_firstlight", "licensed_reusable")

ALLOWED_USES = ("benchmark_evidence", "pattern_learning", "constraint_extraction",
                "layout_review", "signoff_expectation", "component_selection_guidance")
FORBIDDEN_DEFAULT = ("direct_schematic_copy", "direct_layout_copy", "direct_bom_copy",
                     "production_reuse_without_review")

DATE_ADDED = "2026-07-06"


def manifest_schema():
    return {
        "version": "v1",
        "required_fields": ["name", "board_class", "source_name",
                            "source_url_or_local_path", "source_type", "license_status",
                            "trust_classification", "direct_reuse", "allowed_uses",
                            "forbidden_uses", "applies_to_fl1_boards", "extracted_patterns",
                            "extracted_constraints", "extracted_required_features",
                            "known_limitations", "provenance", "date_added"],
        "trust_classifications": list(TRUST),
        "reusable_trust": list(REUSABLE),
        "allowed_uses_vocabulary": list(ALLOWED_USES),
        "forbidden_uses_default": list(FORBIDDEN_DEFAULT),
        "default_direct_reuse": {"internal_firstlight": True, "licensed_reusable": True,
                                 "manufacturer_reference_only": False,
                                 "open_source_needs_license_review": False,
                                 "idea_only": False, "unknown_untrusted": False},
        "status_values": ["imported", "needs_source_file", "needs_license_review"],
    }


def _ref(name, board_class, trust, source_name, path, source_type, applies, **kw):
    direct = trust in REUSABLE
    status = kw.get("status", "imported" if (trust in REUSABLE or kw.get("local")) else "needs_source_file")
    allowed = kw.get("allowed_uses") or (
        list(ALLOWED_USES) if trust == "internal_firstlight"
        else ["benchmark_evidence", "pattern_learning", "constraint_extraction", "layout_review"]
        if trust == "manufacturer_reference_only"
        else ["benchmark_evidence", "pattern_learning", "constraint_extraction"])
    forbidden = kw.get("forbidden_uses") or (
        [] if trust == "internal_firstlight" else list(FORBIDDEN_DEFAULT))
    assert trust in TRUST
    return {
        "name": name, "board_class": board_class, "source_name": source_name,
        "source_url_or_local_path": path, "source_type": source_type,
        "license_status": kw.get("license_status",
                                 "FirstLight-owned" if trust == "internal_firstlight"
                                 else "manufacturer eval, reference-only"
                                 if trust == "manufacturer_reference_only"
                                 else "unreviewed" if trust == "open_source_needs_license_review"
                                 else "unknown"),
        "trust_classification": trust, "direct_reuse": direct,
        "allowed_uses": allowed, "forbidden_uses": forbidden,
        "applies_to_fl1_boards": applies,
        "extracted_patterns": kw.get("patterns", []),
        "extracted_constraints": kw.get("constraints", []),
        "extracted_required_features": kw.get("features", []),
        "known_limitations": kw.get("limitations", []),
        "provenance": kw.get("provenance", "FL-1 program Phase 13 D.5"),
        "date_added": DATE_ADDED, "status": status,
    }


# ---- internal FirstLight references (trusted, generated by us) ----------------
INTERNAL = [
    _ref("ads1115_measurement_front_end", "ADS1115 measurement front-end",
         "internal_firstlight", "FirstLight run fl1-cal-reference (renamed)",
         "public/runs/fl1-cal-reference", "generated_board",
         ["dmm_lite", "calibration_reference", "power_current_monitor"], local=True,
         patterns=["ADC input path", "I2C pullups", "decoupling", "test points"],
         features=["ADS1115 on I2C", "measurement path"],
         limitations=["MEASUREMENT FRONT-END ONLY — usable as an ADC-measurement "
                      "SUB-PATTERN, NOT as a calibration/reference board reference"]),
    _ref("ads1115_recovered_board", "Recovered ADS1115 board", "internal_firstlight",
         "FirstLight recovery-loop board", "public/runs/recovery", "generated_board",
         ["dmm_lite", "calibration_reference"], local=True,
         patterns=["board_margin recovery for fine-pitch", "enlarge-to-route"],
         features=["recovered fine-pitch routing"], limitations=["fine-pitch escape still 2-drop only"]),
    _ref("ads1115_pattern_backed", "Pattern-backed ADS1115 board", "internal_firstlight",
         "FirstLight pattern library", "public/runs/adv-analog", "generated_board",
         ["dmm_lite", "calibration_reference"], local=True,
         patterns=["learned board_margin hint", "precision-ADC pattern"],
         features=["pattern-applied placement"]),
    _ref("usb_hs_diffpair_demo", "USB high-speed differential-pair demo",
         "internal_firstlight", "FirstLight run usb-hs-demo", "public/runs/usb-hs-demo",
         "generated_board", ["external_instrument_interface", "rf_50ohm_interface"], local=True,
         patterns=["routed+checked differential pair", "length/skew check"],
         features=["real diff-pair routing"], limitations=["impedance advisory-only"]),
    _ref("fl1_calibration_reference_attempt", "Real FL-1 Calibration/Reference board attempt",
         "internal_firstlight", "FirstLight run fl1-cal-board", "public/runs/fl1-cal-board",
         "generated_board", ["calibration_reference"], local=True,
         patterns=["reference + divider + ADC-measures-both", "shared I2C bus", "cal test points"],
         features=["REF3025 reference", "RCAL divider -> REF_DIV", "ADS1115 reads REF_OUT+REF_DIV",
                   "24LC02 board-ID EEPROM", "FL-1 bus connector"],
         limitations=["do_not_build: ADS1115 4-way fine-pitch escape blocked_by_grid_resolution"]),
    _ref("shared_bus_i2c_demo", "Shared-bus I2C demo", "internal_firstlight",
         "FirstLight shared_bus", "hardware/planner/shared_bus.py", "generated_pattern",
         ["calibration_reference", "dmm_lite", "power_current_monitor", "digital_bringup"], local=True,
         patterns=["I2C multi-drop trunk", "pullups from master", "per-device address"],
         features=["multi-drop connectivity checked"]),
    _ref("fl1_instrument_bus_v1", "FL-1 instrument bus v1", "internal_firstlight",
         "FirstLight fl1_boards", "hardware/planner/fl1_boards.py", "spec",
         ["calibration_reference", "digital_bringup", "external_instrument_interface"], local=True,
         patterns=["power rails + protected rails + control bus + trigger"],
         features=["FL-1 bus connector pinout"], limitations=["v1 — not final"]),
    _ref("fl1_board_family_architecture", "FL-1 board family architecture map",
         "internal_firstlight", "FirstLight fl1_boards", "hardware/planner/fl1_boards.py", "spec",
         ["*"], local=True, patterns=["10-board family readiness ranking"],
         features=["architecture map"]),
    _ref("fl1_reference_pattern_readiness", "FL-1 reference pattern readiness map",
         "internal_firstlight", "FirstLight fl1_boards", "hardware/planner/fl1_boards.py", "spec",
         ["*"], local=True, patterns=["pattern readiness per board"], features=["gap map"]),
]

# ---- external references — placeholders, NON-reusable by default -------------
EXTERNAL = [
    _ref("precision_adc_measurement_ref", "Precision ADC / measurement path",
         "manufacturer_reference_only", "ADC vendor eval board (reference-only)",
         "references/precision_adc/EVAL.pdf", "manufacturer_eval",
         ["calibration_reference", "dmm_lite", "power_current_monitor"],
         patterns=["ADC input path", "I2C pullups", "analog quiet zone", "reference usage",
                   "input protection", "test points", "calibration loopback",
                   "fine-pitch escape warning"],
         limitations=["reference-only; fine-pitch escape must be solved by FirstLight"]),
    _ref("precision_voltage_reference_ref", "Precision voltage reference / cal source",
         "manufacturer_reference_only", "Voltage-reference vendor app note",
         "references/vref/APPNOTE.pdf", "app_note",
         ["calibration_reference", "dmm_lite", "stimulus_funcgen_lite"],
         patterns=["reference output", "RC filtering", "divider/ladder", "low-noise routing",
                   "labeled calibration nodes", "test points"]),
    _ref("current_sense_power_monitor_ref", "Current sense / power monitor",
         "manufacturer_reference_only", "Current-monitor vendor eval",
         "references/current_sense/EVAL.pdf", "manufacturer_eval",
         ["power_current_monitor", "dmm_lite"],
         patterns=["shunt placement", "Kelvin sense", "current/voltage measurement",
                   "eFuse/protection", "thermal warning", "calibration points"]),
    _ref("relay_probe_matrix_ref", "Relay / probe matrix", "open_source_needs_license_review",
         "Open-source relay matrix (license unreviewed)", "references/relay_matrix/",
         "open_source_kicad", ["relay_probe_matrix", "digital_bringup"],
         patterns=["relay driver", "flyback/protection", "channel matrix",
                   "connector strategy", "isolation/clearance", "test hooks"]),
    _ref("digital_bringup_debug_ref", "Digital bring-up / debug interface",
         "open_source_needs_license_review", "Open-source debug adapter (license unreviewed)",
         "references/debug_iface/", "open_source_kicad",
         ["digital_bringup", "external_instrument_interface"],
         patterns=["SWD", "JTAG", "UART", "I2C", "SPI", "CAN", "RS485", "protected IO",
                   "level shifting", "board ID EEPROM"]),
    _ref("dac_stimulus_ref", "DAC / stimulus", "manufacturer_reference_only",
         "DAC vendor eval board", "references/dac/EVAL.pdf", "manufacturer_eval",
         ["stimulus_funcgen_lite", "calibration_reference"],
         patterns=["DAC output", "reference voltage", "output buffer", "filter placeholder",
                   "calibration loopback", "output protection"],
         limitations=["NO function-generator-class quality"]),
    _ref("logic_capture_protected_input_ref", "Logic capture / protected input",
         "open_source_needs_license_review", "Open-source logic input front end (unreviewed)",
         "references/logic_capture/", "open_source_kicad",
         ["logic_capture", "digital_bringup"],
         patterns=["protected digital inputs", "level shifting", "trigger input",
                   "thresholding", "FPGA/module interface"],
         limitations=["NO logic-analyzer-class timing"]),
    _ref("rf_50ohm_sma_bnc_ref", "RF/50 ohm/SMA/BNC interface", "manufacturer_reference_only",
         "Connector vendor RF layout guide", "references/rf_50ohm/GUIDE.pdf", "app_note",
         ["external_instrument_interface", "rf_50ohm_interface"],
         patterns=["SMA/BNC placement", "50 ohm advisory trace", "return path",
                   "ground stitching", "AC/DC coupling", "termination"],
         limitations=["NO RF guarantee; 50 ohm is an estimate"]),
    _ref("scope_lite_highspeed_adc_ref", "Scope-lite / high-speed ADC reference",
         "idea_only", "no validated reference", "references/scope_lite/", "idea",
         ["scope_lite"],
         patterns=["ADC front end", "input attenuation", "protection", "clocking",
                   "capture interface", "calibration path"],
         limitations=["NOT ready unless real ADC + clocking + capture memory + analog "
                      "signoff are implemented — scope-lite stays unsupported/do_not_build"]),
]


def library():
    return {"version": "v1", "internal_count": len(INTERNAL), "external_count": len(EXTERNAL),
            "references": INTERNAL + EXTERNAL}


def refs_for_board(board_name):
    return [r for r in (INTERNAL + EXTERNAL)
            if board_name in r["applies_to_fl1_boards"] or "*" in r["applies_to_fl1_boards"]]


def pattern_extraction():
    """Extracted patterns/constraints per reference (evidence-only; guessed items
    stay advisory via the reference's own status)."""
    out = []
    for r in INTERNAL + EXTERNAL:
        out.append({
            "reference": r["name"], "trust": r["trust_classification"],
            "status": r["status"], "direct_reuse": r["direct_reuse"],
            "required_blocks": r["extracted_patterns"],
            "required_features": r["extracted_required_features"],
            "required_constraints": r["extracted_constraints"],
            "known_unsupported_risks": r["known_limitations"],
            "confidence": "evidence" if r["status"] == "imported" else "needs_review",
        })
    return {"version": "v1", "extractions": out}


def coverage_for(board_name):
    """Reference coverage summary for a board — feeds the benchmark scorer."""
    refs = refs_for_board(board_name)
    internal = [r for r in refs if r["trust_classification"] == "internal_firstlight"]
    manuf = [r for r in refs if r["trust_classification"] == "manufacturer_reference_only"]
    opensrc = [r for r in refs if r["trust_classification"] == "open_source_needs_license_review"]
    reusable = [r for r in refs if r["direct_reuse"]]
    needs_file = [r for r in refs if r["status"] == "needs_source_file"]
    unlicensed = [r for r in refs if r["trust_classification"] in
                  ("open_source_needs_license_review", "unknown_untrusted")]
    risk = ("high" if opensrc and not internal else "medium" if (manuf or opensrc) and internal
            else "low" if internal else "none")
    return {
        "board": board_name, "reference_count": len(refs),
        "internal_reference_coverage": len(internal),
        "manufacturer_reference_coverage": len(manuf),
        "open_source_reference_coverage": len(opensrc),
        "reusable_reference_count": len(reusable),
        "unlicensed_reference_count": len(unlicensed),
        "needs_source_file_count": len(needs_file),
        "reference_risk_level": risk,
        # score in [0,1]: internal refs carry weight; external add confidence but capped
        "reference_coverage_score": round(min(1.0, 0.5 * bool(internal) +
                                          0.15 * min(len(internal), 2) +
                                          0.1 * min(len(manuf) + len(opensrc), 2)), 2),
    }


if __name__ == "__main__":
    print(json.dumps(library(), indent=1))
